### ISSUE TITLE
Can not resolve path properly for resources defined over variables

### ISSUE THREAD

**Issue by Grygir** [bholloway/resolve-url-loader#126]
**resolve-url-loader** in the version 3.1.0, has been changed the way how references from sass variables are resolved.

When sass variable contains relative reference to resource file, that reference got resolved from the place where the variable is used, not from the place where the variable is defined.
```
|- src
   |- images
      |- a.png
   |- styles
      |- mobile
         |- main.scss
      |- _variabls.scss
      |- main.scss
```
**src/styles/_variabls.scss**
```scss
$background: url('../images/a.png') !default;
```

**src/styles/main.scss**
```scss
@import "variables";
.head {
    background: $background;
}
```

And **src/styles/mobile/main.scss**
```scss
@import "../variables";
.head {
    background: $background;
}
```

Leads to the error
```
ERROR in ./src/styles/mobile/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../images/a.png' in '/src/styles/mobile'
```

Note. In version 2.3.1 resources from variables are resolved fine.
