### ISSUE TITLE
[Bug] @page css properties widths generating warnings

### ISSUE THREAD

**Issue by luchillo17** [bholloway/resolve-url-loader#39]
Using the following styles for printing in any css generates warnings, most likely because of the size units being `mm`, `in` or `cm`:

```css
@page {
    width:44mm;
    size:8.5in 11in; 
    margin: 0.5cm !important;
};
```

Warning:

![image](https://cloud.githubusercontent.com/assets/9698639/21367837/b3ddb5c8-c6cd-11e6-9df4-6d26e4349e78.png)
