### ISSUE TITLE
Module build failed: Unclosed block

### ISSUE THREAD

**Issue by evilebottnawi** [bholloway/resolve-url-loader#56]
Original issue https://github.com/webpack-contrib/sass-loader/issues/354 (have minimal reproducible test repo).

Using: latest version `webpack` and loaders.

Short:
1. Install `"bootstrap": "^4.0.0-alpha.6",`.
2. Add loader:
```shell
{
          test: /\.scss$/,
          loader: ExtractTextPlugin.extract({
              fallbackLoader: 'style-loader',
              loader: 'css-loader!resolve-url-loader!sass-loader?sourceMap'
            })
        }
```
3. Create reproduce-bug.scss with content:
```scss
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/navbar";

.game-header-image {
	@include media-breakpoint-down(sm) {
		content: '';
	}
}
```
4. Add `require('/path/to/reproduce-bug.scss')`
5. Run assembly.

Error:
```shell
Module build failed: Unclosed block (217:4)
    
      215 |   .navbar-toggleable-lg>.container {
      216 |     padding-right: 0;
    > 217 |     padding-left: 0;
          |    ^
      218 |   }
      219 | }
      220 | 
```

Seems bug in `rework` parser (or stringfier). Now `rework` is outdate and don't fix bugs in main repo, maybe be best switch to `postcss`. Thanks!
